### ISSUE TITLE
proxies代理参数怎么配置

### ISSUE THREAD

**Issue by ruimax** [sanyueyu/gulp-mock-server#16]
按照例子配置不成功啊
proxies: [{
            source: '/abc', 
            target: 'http://localhost:8080/abc', 
            options: {
                headers: {'ABC_HEADER': 'abc'}
            }
        }]

**Comment by sanyueyu** [comment]
具体使用的是这个中间件 https://www.npmjs.com/package/proxy-middleware

**Comment by ruimax** [comment]
谢谢，不过还是用了http-proxy-middleware这个代理中间件
