### ISSUE TITLE
routes support

### ISSUE THREAD

**Issue by yairEO** [sanyueyu/gulp-mock-server#24]
I really need routes support, so the mock server will give mock JSON files for each "real" URL path. 

### https://internal.domain.com/proxy/abc/foo/getUserData?id=123

````
module.exports = {
  route: "/proxy/abc/foo/getUserData",
  response: './userData.json'
}
````

**Comment by sanyueyu** [comment]
thank you,i will do it lately. and I am pleasure you can contribute it ,thank you

**Comment by sanyueyu** [comment]
i add route in 1.1.4  but it is a url
